### ISSUE TITLE
Problem in Windows 10 Pro

### ISSUE THREAD

**Issue by M2000Interpreter** [wqweto/ClipBar#1]
At Line 82 frmMain
Fault statement:
Clipboard.SetData picBarCode.Picture

This is the solution:
Clipboard.SetData picBarCode.Image, vbCFBitmap

**Comment by wqweto** [comment]
This raises `Specified format doesn't match format of data` error here.

Better fix would be to use `vbCFMetafile` as the the barcode is rendered as a vector image in WMF format so it can be scaled to variable (large) sizes without loss of fidelity.

Edit: Fixed in af8443ed4dbe3eb74e39e210eb4f44ed7539f868
